title: "ChatVoice"
email: ximenasantiagoo@outlook.com
description: "Documentación de un ChatVoice."

baseurl: "/chatvoice-documentation"
url: ""

theme: just-the-docs

plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/


