# Título de la página 
title: "Documentación ChatVoice"
# Correo del propietario 
email: ximenasantiagoo@outlook.com
# Breve descripción de la página
description: "Documentación ChatVoice."

baseurl: "/chatvoice-documentation" # Nombre del repositorio
url: "https://ximenaasantiagoo.github.io" # Dominio de GitHub Pages
# Información adicional
twitter_username: ximenasantiagoo
github_username: ximenaasantiagoo

# Configuración del tema 
theme: just-the-docs

# Plugins
plugins:
  - jekyll-feed

# Exclusiones
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - vendor/
